server:
  port: 8010

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/teststeisclientdb
    username: postgres
    password: 7727ww7727

  freemarker:
    suffix: .ftlh
  jpa:
    generate-ddl: true
    show-sql: true
#    hibernate:
#      ddl-auto: create

