server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/teststeisclientdb
    username: ${db_username:deathsmell}
    password: ${db_password:pAsSw0rt}


  freemarker:
    suffix: .ftlh
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

